development:
 password: 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
 theme_id: 84033306727
 store: avexplustest.myshopify.com
 ignore_files:
    - config/settings_data.json 

production:
  password: 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
  theme_id: 
  store: avexplustest.myshopify.com
  ignore_files:
    - config/settings_data.json 