development:
 password: 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
 theme_id: 117914206370
 store: nicole-avex-test-store.myshopify.com
 ignore_files:
    - config/settings_data.json 

production:
  password: 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
  theme_id: 113495048353
  store: nicole-avex-test-store.myshopify.com
  ignore_files:
    - config/settings_data.json 